// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: statistics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOrderStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrderStatisticsRequest) Reset() {
	*x = UserOrderStatisticsRequest{}
	mi := &file_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderStatisticsRequest) ProtoMessage() {}

func (x *UserOrderStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderStatisticsRequest.ProtoReflect.Descriptor instead.
func (*UserOrderStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *UserOrderStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserOrderStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders   int32                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	OrderIds      []string               `protobuf:"bytes,2,rep,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrderStatisticsResponse) Reset() {
	*x = UserOrderStatisticsResponse{}
	mi := &file_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderStatisticsResponse) ProtoMessage() {}

func (x *UserOrderStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserOrderStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *UserOrderStatisticsResponse) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *UserOrderStatisticsResponse) GetOrderIds() []string {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

type UserStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatisticsRequest) Reset() {
	*x = UserStatisticsRequest{}
	mi := &file_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsRequest) ProtoMessage() {}

func (x *UserStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsRequest.ProtoReflect.Descriptor instead.
func (*UserStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *UserStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserStatisticsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders    int32                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	TotalProducts  int32                  `protobuf:"varint,2,opt,name=total_products,json=totalProducts,proto3" json:"total_products,omitempty"`
	MostActiveHour string                 `protobuf:"bytes,3,opt,name=most_active_hour,json=mostActiveHour,proto3" json:"most_active_hour,omitempty"`
	TotalUsers     int32                  `protobuf:"varint,4,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserStatisticsResponse) Reset() {
	*x = UserStatisticsResponse{}
	mi := &file_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsResponse) ProtoMessage() {}

func (x *UserStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *UserStatisticsResponse) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *UserStatisticsResponse) GetTotalProducts() int32 {
	if x != nil {
		return x.TotalProducts
	}
	return 0
}

func (x *UserStatisticsResponse) GetMostActiveHour() string {
	if x != nil {
		return x.MostActiveHour
	}
	return ""
}

func (x *UserStatisticsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

var File_statistics_proto protoreflect.FileDescriptor

const file_statistics_proto_rawDesc = "" +
	"\n" +
	"\x10statistics.proto\x12\x0fecommerce.proto\"5\n" +
	"\x1aUserOrderStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"]\n" +
	"\x1bUserOrderStatisticsResponse\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x05R\vtotalOrders\x12\x1b\n" +
	"\torder_ids\x18\x02 \x03(\tR\borderIds\"0\n" +
	"\x15UserStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xad\x01\n" +
	"\x16UserStatisticsResponse\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x05R\vtotalOrders\x12%\n" +
	"\x0etotal_products\x18\x02 \x01(\x05R\rtotalProducts\x12(\n" +
	"\x10most_active_hour\x18\x03 \x01(\tR\x0emostActiveHour\x12\x1f\n" +
	"\vtotal_users\x18\x04 \x01(\x05R\n" +
	"totalUsers2\xef\x01\n" +
	"\x11StatisticsService\x12t\n" +
	"\x17GetUserOrdersStatistics\x12+.ecommerce.proto.UserOrderStatisticsRequest\x1a,.ecommerce.proto.UserOrderStatisticsResponse\x12d\n" +
	"\x11GetUserStatistics\x12&.ecommerce.proto.UserStatisticsRequest\x1a'.ecommerce.proto.UserStatisticsResponseB\x11Z\x0fecommerce/protob\x06proto3"

var (
	file_statistics_proto_rawDescOnce sync.Once
	file_statistics_proto_rawDescData []byte
)

func file_statistics_proto_rawDescGZIP() []byte {
	file_statistics_proto_rawDescOnce.Do(func() {
		file_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statistics_proto_rawDesc), len(file_statistics_proto_rawDesc)))
	})
	return file_statistics_proto_rawDescData
}

var file_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_statistics_proto_goTypes = []any{
	(*UserOrderStatisticsRequest)(nil),  // 0: ecommerce.proto.UserOrderStatisticsRequest
	(*UserOrderStatisticsResponse)(nil), // 1: ecommerce.proto.UserOrderStatisticsResponse
	(*UserStatisticsRequest)(nil),       // 2: ecommerce.proto.UserStatisticsRequest
	(*UserStatisticsResponse)(nil),      // 3: ecommerce.proto.UserStatisticsResponse
}
var file_statistics_proto_depIdxs = []int32{
	0, // 0: ecommerce.proto.StatisticsService.GetUserOrdersStatistics:input_type -> ecommerce.proto.UserOrderStatisticsRequest
	2, // 1: ecommerce.proto.StatisticsService.GetUserStatistics:input_type -> ecommerce.proto.UserStatisticsRequest
	1, // 2: ecommerce.proto.StatisticsService.GetUserOrdersStatistics:output_type -> ecommerce.proto.UserOrderStatisticsResponse
	3, // 3: ecommerce.proto.StatisticsService.GetUserStatistics:output_type -> ecommerce.proto.UserStatisticsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_statistics_proto_init() }
func file_statistics_proto_init() {
	if File_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistics_proto_rawDesc), len(file_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistics_proto_goTypes,
		DependencyIndexes: file_statistics_proto_depIdxs,
		MessageInfos:      file_statistics_proto_msgTypes,
	}.Build()
	File_statistics_proto = out.File
	file_statistics_proto_goTypes = nil
	file_statistics_proto_depIdxs = nil
}
